/**
 * Represents the evidence provided to the AI failure-analysis engine.
 *
 * This model intentionally contains test execution information rather
 * than AI-specific concepts. The analyzer can therefore consume failures
 * from different automation layers such as:
 *
 * - Web / Playwright
 * - API
 * - Mobile / Appium
 * - Future automation technologies
 *
 * Keeping the request model framework-oriented allows the AI layer to
 * remain independent from a particular test runner.
 */
export interface FailureAnalysisRequest {

    /**
     * Name of the test that failed.
     */
    testName: string;

    /**
     * Automation layer that produced the failure.
     */
    testType: "WEB" | "API" | "MOBILE" | "UNKNOWN";

    /**
     * Human-readable error message generated by the test framework.
     */
    errorMessage: string;

    /**
     * Optional stack trace associated with the failure.
     */
    stackTrace?: string;

    /**
     * Path of the test file that produced the failure.
     */
    testFile?: string;

    /**
     * Optional expected value or behavior.
     */
    expected?: string;

    /**
     * Optional actual value or behavior observed during execution.
     */
    actual?: string;

    /**
     * Additional contextual information that may help AI analysis.
     *
     * Examples:
     * - URL
     * - API endpoint
     * - HTTP status code
     * - locator
     * - device information
     * - browser information
     * - environment name
     */
    metadata?: Record<string, unknown>;
}